eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
spring:
  application:
    name: gateway
server:
  port: 8084
zuul:
  routes:
    api-a: 
      path: /discovery/**
      service-id: discovery
    study: ##这里的配置表示，访问/it/** 直接重定向到http://www.ityouknow.com/**
      path: /study/**
      url: http://www.mi.com/
    authenticate: 
      path: /authenticate/**
      url: http://www.baidu.com/


